import os
from datetime import datetime

def generate_markdown_report(reports: list, filename: str = "reports/audit_report.md") -> str:
    """Takes audit results and exports a clean, minimalist Markdown report without emojis."""
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    total_tests = len(reports)
    failed_tests = sum(1 for r in reports if r.get("overall_status") != "PASS")
    passed_tests = total_tests - failed_tests
    success_rate = (passed_tests / total_tests) * 100 if total_tests > 0 else 0

    md_content = f"""# Audit Report

* Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
* Summary: {passed_tests}/{total_tests} Passed ({success_rate:.1f}%)

---
"""

    for report in reports:
        status = report.get("overall_status", "UNKNOWN")
        md_content += f"### {report.get('test_name')} [{status}]\n\n"
        
        if "error" in report:
            md_content += f"Error: {report['error']}\n\n"
            continue

        checks = report.get("checks", {})
        
        # Schema Check
        schema = checks.get("schema", {})
        schema_status = "PASS" if schema.get("passed") else "FAIL"
        md_content += f"- Schema: {schema_status}"
        if schema.get("error"):
            md_content += f" ({schema['error']})"
        md_content += "\n"

        # Latency Check
        latency = checks.get("latency", {})
        latency_status = "PASS" if latency.get("passed") else "FAIL"
        duration = latency.get("duration_sec", "N/A")
        md_content += f"- Latency: {latency_status} ({duration}s)\n"

        # Semantic Faithfulness Check
        semantic = checks.get("semantic_faithfulness", {})
        semantic_status = "PASS" if semantic.get("passed") else "FAIL"
        md_content += f"- Semantic: {semantic_status}\n"
        
        details = semantic.get("details", "")
        if details:
            # Extract just the rationale text cleanly
            clean_details = details.replace("VERDICT: PASS\n", "").replace("VERDICT: FAIL\n", "").replace("\n", " ")
            md_content += f"  - Rationale: {clean_details}\n"

        md_content += "\n"

    md_content += "---\nGenerated by AuditLLM."

    with open(filename, "w", encoding="utf-8") as f:
        f.write(md_content)
    
    return filename